/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SevaRouteImport } from './routes/seva'
import { Route as RatnaRouteImport } from './routes/ratna'
import { Route as RashifalRouteImport } from './routes/rashifal'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NakshatraRouteImport } from './routes/nakshatra'
import { Route as MargdarshanRouteImport } from './routes/margdarshan'
import { Route as JyotishRouteImport } from './routes/jyotish'
import { Route as HastrekhaRouteImport } from './routes/hastrekha'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DashaRouteImport } from './routes/dasha'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AnkJyotishRouteImport } from './routes/ank-jyotish'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MargdarshanIndexRouteImport } from './routes/margdarshan.index'
import { Route as LekhIndexRouteImport } from './routes/lekh.index'
import { Route as MargdarshanCareerRouteImport } from './routes/margdarshan.career'
import { Route as LekhSlugRouteImport } from './routes/lekh.$slug'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SevaRoute = SevaRouteImport.update({
  id: '/seva',
  path: '/seva',
  getParentRoute: () => rootRouteImport,
} as any)
const RatnaRoute = RatnaRouteImport.update({
  id: '/ratna',
  path: '/ratna',
  getParentRoute: () => rootRouteImport,
} as any)
const RashifalRoute = RashifalRouteImport.update({
  id: '/rashifal',
  path: '/rashifal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NakshatraRoute = NakshatraRouteImport.update({
  id: '/nakshatra',
  path: '/nakshatra',
  getParentRoute: () => rootRouteImport,
} as any)
const MargdarshanRoute = MargdarshanRouteImport.update({
  id: '/margdarshan',
  path: '/margdarshan',
  getParentRoute: () => rootRouteImport,
} as any)
const JyotishRoute = JyotishRouteImport.update({
  id: '/jyotish',
  path: '/jyotish',
  getParentRoute: () => rootRouteImport,
} as any)
const HastrekhaRoute = HastrekhaRouteImport.update({
  id: '/hastrekha',
  path: '/hastrekha',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashaRoute = DashaRouteImport.update({
  id: '/dasha',
  path: '/dasha',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AnkJyotishRoute = AnkJyotishRouteImport.update({
  id: '/ank-jyotish',
  path: '/ank-jyotish',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MargdarshanIndexRoute = MargdarshanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MargdarshanRoute,
} as any)
const LekhIndexRoute = LekhIndexRouteImport.update({
  id: '/lekh/',
  path: '/lekh/',
  getParentRoute: () => rootRouteImport,
} as any)
const MargdarshanCareerRoute = MargdarshanCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => MargdarshanRoute,
} as any)
const LekhSlugRoute = LekhSlugRouteImport.update({
  id: '/lekh/$slug',
  path: '/lekh/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ank-jyotish': typeof AnkJyotishRoute
  '/contact': typeof ContactRoute
  '/dasha': typeof DashaRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/hastrekha': typeof HastrekhaRoute
  '/jyotish': typeof JyotishRoute
  '/margdarshan': typeof MargdarshanRouteWithChildren
  '/nakshatra': typeof NakshatraRoute
  '/privacy': typeof PrivacyRoute
  '/rashifal': typeof RashifalRoute
  '/ratna': typeof RatnaRoute
  '/seva': typeof SevaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/lekh/$slug': typeof LekhSlugRoute
  '/margdarshan/career': typeof MargdarshanCareerRoute
  '/lekh/': typeof LekhIndexRoute
  '/margdarshan/': typeof MargdarshanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ank-jyotish': typeof AnkJyotishRoute
  '/contact': typeof ContactRoute
  '/dasha': typeof DashaRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/hastrekha': typeof HastrekhaRoute
  '/jyotish': typeof JyotishRoute
  '/nakshatra': typeof NakshatraRoute
  '/privacy': typeof PrivacyRoute
  '/rashifal': typeof RashifalRoute
  '/ratna': typeof RatnaRoute
  '/seva': typeof SevaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/lekh/$slug': typeof LekhSlugRoute
  '/margdarshan/career': typeof MargdarshanCareerRoute
  '/lekh': typeof LekhIndexRoute
  '/margdarshan': typeof MargdarshanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ank-jyotish': typeof AnkJyotishRoute
  '/contact': typeof ContactRoute
  '/dasha': typeof DashaRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/hastrekha': typeof HastrekhaRoute
  '/jyotish': typeof JyotishRoute
  '/margdarshan': typeof MargdarshanRouteWithChildren
  '/nakshatra': typeof NakshatraRoute
  '/privacy': typeof PrivacyRoute
  '/rashifal': typeof RashifalRoute
  '/ratna': typeof RatnaRoute
  '/seva': typeof SevaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/lekh/$slug': typeof LekhSlugRoute
  '/margdarshan/career': typeof MargdarshanCareerRoute
  '/lekh/': typeof LekhIndexRoute
  '/margdarshan/': typeof MargdarshanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ank-jyotish'
    | '/contact'
    | '/dasha'
    | '/disclaimer'
    | '/faq'
    | '/hastrekha'
    | '/jyotish'
    | '/margdarshan'
    | '/nakshatra'
    | '/privacy'
    | '/rashifal'
    | '/ratna'
    | '/seva'
    | '/sitemap.xml'
    | '/terms'
    | '/testimonials'
    | '/lekh/$slug'
    | '/margdarshan/career'
    | '/lekh/'
    | '/margdarshan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ank-jyotish'
    | '/contact'
    | '/dasha'
    | '/disclaimer'
    | '/faq'
    | '/hastrekha'
    | '/jyotish'
    | '/nakshatra'
    | '/privacy'
    | '/rashifal'
    | '/ratna'
    | '/seva'
    | '/sitemap.xml'
    | '/terms'
    | '/testimonials'
    | '/lekh/$slug'
    | '/margdarshan/career'
    | '/lekh'
    | '/margdarshan'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ank-jyotish'
    | '/contact'
    | '/dasha'
    | '/disclaimer'
    | '/faq'
    | '/hastrekha'
    | '/jyotish'
    | '/margdarshan'
    | '/nakshatra'
    | '/privacy'
    | '/rashifal'
    | '/ratna'
    | '/seva'
    | '/sitemap.xml'
    | '/terms'
    | '/testimonials'
    | '/lekh/$slug'
    | '/margdarshan/career'
    | '/lekh/'
    | '/margdarshan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnkJyotishRoute: typeof AnkJyotishRoute
  ContactRoute: typeof ContactRoute
  DashaRoute: typeof DashaRoute
  DisclaimerRoute: typeof DisclaimerRoute
  FaqRoute: typeof FaqRoute
  HastrekhaRoute: typeof HastrekhaRoute
  JyotishRoute: typeof JyotishRoute
  MargdarshanRoute: typeof MargdarshanRouteWithChildren
  NakshatraRoute: typeof NakshatraRoute
  PrivacyRoute: typeof PrivacyRoute
  RashifalRoute: typeof RashifalRoute
  RatnaRoute: typeof RatnaRoute
  SevaRoute: typeof SevaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  LekhSlugRoute: typeof LekhSlugRoute
  LekhIndexRoute: typeof LekhIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seva': {
      id: '/seva'
      path: '/seva'
      fullPath: '/seva'
      preLoaderRoute: typeof SevaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratna': {
      id: '/ratna'
      path: '/ratna'
      fullPath: '/ratna'
      preLoaderRoute: typeof RatnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rashifal': {
      id: '/rashifal'
      path: '/rashifal'
      fullPath: '/rashifal'
      preLoaderRoute: typeof RashifalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nakshatra': {
      id: '/nakshatra'
      path: '/nakshatra'
      fullPath: '/nakshatra'
      preLoaderRoute: typeof NakshatraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/margdarshan': {
      id: '/margdarshan'
      path: '/margdarshan'
      fullPath: '/margdarshan'
      preLoaderRoute: typeof MargdarshanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jyotish': {
      id: '/jyotish'
      path: '/jyotish'
      fullPath: '/jyotish'
      preLoaderRoute: typeof JyotishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hastrekha': {
      id: '/hastrekha'
      path: '/hastrekha'
      fullPath: '/hastrekha'
      preLoaderRoute: typeof HastrekhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dasha': {
      id: '/dasha'
      path: '/dasha'
      fullPath: '/dasha'
      preLoaderRoute: typeof DashaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ank-jyotish': {
      id: '/ank-jyotish'
      path: '/ank-jyotish'
      fullPath: '/ank-jyotish'
      preLoaderRoute: typeof AnkJyotishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/margdarshan/': {
      id: '/margdarshan/'
      path: '/'
      fullPath: '/margdarshan/'
      preLoaderRoute: typeof MargdarshanIndexRouteImport
      parentRoute: typeof MargdarshanRoute
    }
    '/lekh/': {
      id: '/lekh/'
      path: '/lekh'
      fullPath: '/lekh/'
      preLoaderRoute: typeof LekhIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/margdarshan/career': {
      id: '/margdarshan/career'
      path: '/career'
      fullPath: '/margdarshan/career'
      preLoaderRoute: typeof MargdarshanCareerRouteImport
      parentRoute: typeof MargdarshanRoute
    }
    '/lekh/$slug': {
      id: '/lekh/$slug'
      path: '/lekh/$slug'
      fullPath: '/lekh/$slug'
      preLoaderRoute: typeof LekhSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MargdarshanRouteChildren {
  MargdarshanCareerRoute: typeof MargdarshanCareerRoute
  MargdarshanIndexRoute: typeof MargdarshanIndexRoute
}

const MargdarshanRouteChildren: MargdarshanRouteChildren = {
  MargdarshanCareerRoute: MargdarshanCareerRoute,
  MargdarshanIndexRoute: MargdarshanIndexRoute,
}

const MargdarshanRouteWithChildren = MargdarshanRoute._addFileChildren(
  MargdarshanRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnkJyotishRoute: AnkJyotishRoute,
  ContactRoute: ContactRoute,
  DashaRoute: DashaRoute,
  DisclaimerRoute: DisclaimerRoute,
  FaqRoute: FaqRoute,
  HastrekhaRoute: HastrekhaRoute,
  JyotishRoute: JyotishRoute,
  MargdarshanRoute: MargdarshanRouteWithChildren,
  NakshatraRoute: NakshatraRoute,
  PrivacyRoute: PrivacyRoute,
  RashifalRoute: RashifalRoute,
  RatnaRoute: RatnaRoute,
  SevaRoute: SevaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TestimonialsRoute: TestimonialsRoute,
  LekhSlugRoute: LekhSlugRoute,
  LekhIndexRoute: LekhIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
